# Generated by Django 6.0.1 on 2026-01-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cua_hang', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TramSac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tram', models.CharField(max_length=255)),
                ('dia_chi', models.TextField()),
                ('cong_suat', models.IntegerField()),
                ('loai_sac', models.CharField(max_length=100)),
                ('trang_thai', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhienSac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField()),
                ('thoi_gian_ket_thuc', models.DateTimeField()),
                ('dien_nang_tieu_thu', models.FloatField()),
                ('tram_sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tramsac')),
            ],
        ),
        migrations.CreateModel(
            name='XeDien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_xe', models.CharField(max_length=255)),
                ('hang_san_xuat', models.CharField(max_length=255)),
                ('dung_luong_pin', models.IntegerField()),
                ('tam_di_chuyen', models.IntegerField()),
                ('gia', models.BigIntegerField()),
                ('trang_thai', models.BooleanField(default=True)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuahang')),
            ],
        ),
    ]
