# Generated by Django 6.0.1 on 2026-03-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramsac',
            name='hinh_anh',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
