# Generated by Django 6.0.1 on 2026-03-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tramsac_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='xedien',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='xe_dien_images/'),
        ),
        migrations.AddField(
            model_name='xedien',
            name='noi_bat',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật'),
        ),
        migrations.AddField(
            model_name='xedien',
            name='sap_ve',
            field=models.BooleanField(default=False, verbose_name='Sản phẩm sắp về'),
        ),
        migrations.AlterField(
            model_name='tramsac',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='tram_sac_images/'),
        ),
    ]
