# Generated by Django 6.0.1 on 2026-03-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_xedien_hinh_anh_xedien_noi_bat_xedien_sap_ve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xedien',
            name='anh_phu_1',
            field=models.ImageField(blank=True, null=True, upload_to='xe_dien_images/', verbose_name='Ảnh phụ 1'),
        ),
        migrations.AddField(
            model_name='xedien',
            name='anh_phu_2',
            field=models.ImageField(blank=True, null=True, upload_to='xe_dien_images/', verbose_name='Ảnh phụ 2'),
        ),
        migrations.AddField(
            model_name='xedien',
            name='anh_phu_3',
            field=models.ImageField(blank=True, null=True, upload_to='xe_dien_images/', verbose_name='Ảnh phụ 3'),
        ),
        migrations.AddField(
            model_name='xedien',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
    ]
