# Generated by Django 6.0.1 on 2026-03-31 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_xedien_anh_phu_1_xedien_anh_phu_2_xedien_anh_phu_3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email nhận thông báo')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ giao xe / Liên hệ')),
                ('loai_don', models.CharField(choices=[('A', 'Đặt giữ xe (Không cần thanh toán, giữ 1-2 ngày)'), ('B', 'Đặt cọc online (Thanh toán trước một phần)'), ('C', 'Mua online hoàn toàn (Thanh toán 100%, Giao tận nơi)')], default='A', max_length=1)),
                ('trang_thai', models.CharField(choices=[('Pending', 'Pending (Đang chờ)'), ('Deposit Paid', 'Deposit Paid (Đã đặt cọc)'), ('Paid', 'Paid (Đã thanh toán)'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xedien')),
            ],
        ),
    ]
