# Generated by Django 6.0.1 on 2026-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='so_tien_tra_truoc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Số tiền trả trước'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email nhận thông báo'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='loai_don',
            field=models.CharField(choices=[('A', 'Đặt giữ xe online'), ('B', 'Đặt cọc online'), ('C', 'Mua online hoàn toàn'), ('D', 'Mua trực tiếp - Trả thẳng 100%'), ('E', 'Mua trực tiếp - Trả góp')], default='A', max_length=1),
        ),
    ]
