# Generated by Django 6.0.1 on 2026-04-02 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donhang_so_tien_tra_truoc_alter_donhang_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=255, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.AddField(
            model_name='xedien',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.danhmuc', verbose_name='Danh mục sản phẩm'),
        ),
    ]
