# Generated by Django 6.0.1 on 2026-04-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_danhmuc_xedien_danh_muc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phiensac',
            name='trang_thai',
            field=models.CharField(choices=[('Dang sac', 'Đang sạc'), ('Hoan thanh', 'Hoàn thành')], default='Dang sac', max_length=20),
        ),
        migrations.AddField(
            model_name='phiensac',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phiensac',
            name='dien_nang_tieu_thu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='phiensac',
            name='thoi_gian_ket_thuc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('danh_gia', models.IntegerField(default=5)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.xedien')),
            ],
        ),
        migrations.CreateModel(
            name='KhoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuahang')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xedien')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15)),
                ('dia_chi', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
