# Generated by Django 6.0.1 on 2026-04-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_phiensac_trang_thai_phiensac_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khohang',
            options={'verbose_name': 'Kho hàng', 'verbose_name_plural': 'Kho hàng'},
        ),
        migrations.AlterField(
            model_name='khohang',
            name='so_luong',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='khohang',
            name='xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kho_hang', to='core.xedien'),
        ),
        migrations.AlterUniqueTogether(
            name='khohang',
            unique_together={('xe', 'cua_hang')},
        ),
    ]
