# Generated by Django 6.0.1 on 2026-04-03 16:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_alter_khohang_options_alter_khohang_so_luong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Quản lý Khách hàng',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
            ],
            options={
                'verbose_name': 'Nhân viên cửa hàng',
                'verbose_name_plural': 'Quản lý Nhân viên',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='danh_gia',
            field=models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5),
        ),
    ]
