# Generated by Django 6.0.1 on 2026-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_khachhang_nhanvien_alter_feedback_danh_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='cua_hang_images/'),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
