# Generated by Django 6.0.1 on 2026-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cuahang_hinh_anh_cuahang_lat_cuahang_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='phiensac',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tổng tiền (VNĐ)'),
        ),
    ]
