# Generated by Django 6.0.1 on 2026-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_phiensac_tong_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vai_tro',
            field=models.CharField(choices=[('admin', 'Admin'), ('quan_ly', 'Quản lý'), ('nhan_vien', 'Nhân viên'), ('khach_hang', 'Khách hàng')], default='khach_hang', max_length=20, verbose_name='Vai trò'),
        ),
    ]
