# Generated by Django 6.0.1 on 2026-04-04 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_vai_tro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='nhan_vien_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên tạo đơn'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_mua', to=settings.AUTH_USER_MODEL),
        ),
    ]
