# Generated by Django 6.0.1 on 2026-04-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_donhang_nhan_vien_tao_alter_donhang_khach_hang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú lô hàng')),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cuahang', verbose_name='Nhập vào chi nhánh')),
                ('nhan_vien_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(verbose_name='Số lượng nhập')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xedien')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='core.phieunhapkho')),
            ],
        ),
    ]
