# Generated by Django 6.0.1 on 2026-04-06 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_phieunhapkho_chitietphieunhap'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='bai_gioi_thieu',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bài Giới Thiệu Cửa Hàng'),
        ),
    ]
