# Generated by Django 6.0.1 on 2026-04-06 08:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cuahang_bai_gioi_thieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuahang',
            name='bai_gioi_thieu',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xedien',
            name='mo_ta',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
    ]
