# Generated by Django 6.0.1 on 2026-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cuahang_bai_gioi_thieu_alter_xedien_mo_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xedien',
            name='cua_hang',
        ),
        migrations.AddField(
            model_name='xedien',
            name='cua_hang',
            field=models.ManyToManyField(blank=True, related_name='danh_sach_xe', to='core.cuahang', verbose_name='Có tại chi nhánh'),
        ),
    ]
