# Generated by Django 6.0.1 on 2026-04-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_xedien_cua_hang_xedien_cua_hang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xedien',
            name='anh_phu_1',
        ),
        migrations.RemoveField(
            model_name='xedien',
            name='anh_phu_2',
        ),
        migrations.RemoveField(
            model_name='xedien',
            name='anh_phu_3',
        ),
        migrations.AlterField(
            model_name='xedien',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='xe_dien_images/', verbose_name='Ảnh đại diện'),
        ),
        migrations.CreateModel(
            name='AnhXeDien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xe_dien_images/')),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_anh', to='core.xedien')),
            ],
        ),
    ]
