# Generated by Django 6.0.1 on 2026-04-09 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_xedien_anh_phu_1_remove_xedien_anh_phu_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCauHoTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề cần hỗ trợ')),
                ('noi_dung_hoi', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('noi_dung_tra_loi', models.TextField(blank=True, null=True, verbose_name='Nhân viên trả lời')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_yeu_cau', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
