# Generated by Django 6.0.1 on 2026-04-09 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_yeucauhotro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TinNhanChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('da_doc', models.BooleanField(default=False)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_cua_khach', to=settings.AUTH_USER_MODEL)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_gui_tin_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['thoi_gian'],
            },
        ),
    ]
