# Generated by Django 6.0.1 on 2026-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tinnhanchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='xedien',
            name='ban_chay',
            field=models.BooleanField(default=False, verbose_name='Bán chạy nhất'),
        ),
        migrations.AddField(
            model_name='xedien',
            name='moi_ve',
            field=models.BooleanField(default=False, verbose_name='Hàng mới về'),
        ),
    ]
