# Generated by Django 6.0.1 on 2026-04-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_xedien_ban_chay_xedien_moi_ve'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='cua_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuahang', verbose_name='Chi nhánh nhận xe'),
        ),
    ]
