# Generated by Django 6.0.1 on 2026-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_donhang_cua_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='hinh_thuc_nhan',
            field=models.CharField(choices=[('Tai_cua_hang', 'Nhận xe tại cửa hàng'), ('Giao_tan_noi', 'Giao xe tận nơi')], default='Tai_cua_hang', max_length=20, verbose_name='Hình thức nhận xe'),
        ),
    ]
