# Generated by Django 6.0.1 on 2026-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_donhang_hinh_thuc_nhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ngay_giao_xe',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hẹn giao/nhận xe'),
        ),
    ]
