# Generated by Django 6.0.1 on 2026-04-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_donhang_ngay_giao_xe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cua_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuahang', verbose_name='Chi nhánh làm việc'),
        ),
    ]
