# Generated by Django 6.0.1 on 2026-04-17 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userprofile_cua_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='loai_don',
            field=models.CharField(choices=[('TraThang', 'Thanh toán 100% nhận xe'), ('DatCoc', 'Đặt cọc giữ xe (20.000.000 VNĐ)')], default='A', max_length=20),
        ),
        migrations.CreateModel(
            name='LichLaiThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên khách hàng')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ngay_hen', models.DateField(verbose_name='Ngày hẹn đến')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú của khách')),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận lịch'), ('hoan_thanh', 'Khách đã đến showroom'), ('huy', 'Đã hủy / Khách không đến')], default='cho_xac_nhan', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('cua_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuahang', verbose_name='Chi nhánh đăng ký đến')),
                ('xe_quan_tam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.xedien', verbose_name='Dòng xe quan tâm')),
            ],
            options={
                'verbose_name': 'Lịch Lái Thử / Xem Xe',
                'verbose_name_plural': 'Lịch Lái Thử / Xem Xe',
            },
        ),
    ]
