# Generated by Django 6.0.1 on 2026-04-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_donhang_loai_don_lichlaithu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
