# Generated by Django 6.0.1 on 2026-04-17 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='phiensac',
            name='dien_nang_tieu_thu',
            field=models.FloatField(default=0, verbose_name='Điện năng (kWh)'),
        ),
        migrations.CreateModel(
            name='DanhGiaTram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(default=5, verbose_name='Số sao')),
                ('noi_dung', models.TextField(blank=True, null=True, verbose_name='Nội dung bình luận')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('tram_sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='core.tramsac', verbose_name='Trạm sạc')),
            ],
        ),
    ]
