# Generated by Django 6.0.1 on 2026-04-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_phiensac_dien_nang_tieu_thu_danhgiatram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('loai', models.CharField(choices=[('don_hang', 'Đơn hàng mới'), ('lai_thu', 'Đăng ký lái thử'), ('ho_tro', 'Tin nhắn hỗ trợ'), ('he_thong', 'Hệ thống')], default='he_thong', max_length=20)),
                ('da_doc', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('cua_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_thong_bao', to='core.cuahang')),
            ],
            options={
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
