# Generated by Django 5.2.13 on 2026-04-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_thongbao'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code', models.CharField(max_length=50, unique=True)),
                ('ten_chuong_trinh', models.CharField(max_length=255)),
                ('loai_khuyen_mai', models.CharField(choices=[('tien_mat', 'Giảm tiền mặt'), ('phan_tram', 'Giảm phần trăm'), ('qua_tang', 'Quà tặng kèm')], max_length=50)),
                ('gia_tri', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='tien_giam_gia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khuyen_mai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.khuyenmai'),
        ),
    ]
