# Generated by Django 5.2.13 on 2026-04-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_khuyenmai_donhang_tien_giam_gia_donhang_khuyen_mai'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='chien_luoc',
            field=models.CharField(choices=[('public', 'Hiển thị công khai (Trang chủ)'), ('private', 'Đặc quyền thành viên (Ví Voucher)'), ('lai_thu', 'Tặng kín sau khi lái thử')], default='public', max_length=20),
        ),
    ]
