# Generated by Django 5.2.13 on 2026-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_khuyenmai_chien_luoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='xe_ap_dung',
            field=models.ManyToManyField(blank=True, help_text='Để trống nếu muốn áp dụng cho TẤT CẢ các xe. Trái lại, chỉ áp dụng cho xe được chọn.', to='core.xedien'),
        ),
    ]
