# Generated by Django 5.2.13 on 2026-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_khuyenmai_xe_ap_dung'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='mo_ta_qua_tang',
            field=models.CharField(blank=True, help_text="Nhập mô tả quà tặng nếu loại khuyến mãi là 'Quà tặng kèm' (VD: Tặng sạc di động 2.2kW)", max_length=255, null=True),
        ),
    ]
