# Generated by Django 5.2.13 on 2026-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_khuyenmai_mo_ta_qua_tang'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voucher_da_luu',
            field=models.ManyToManyField(blank=True, related_name='nguoi_dung_da_luu', to='core.khuyenmai'),
        ),
    ]
