# Generated by Django 5.2.13 on 2026-05-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_userprofile_voucher_da_luu'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='loai_don_ap_dung',
            field=models.CharField(choices=[('Tat_ca', 'Áp dụng cho mọi loại đơn'), ('Tra_thang', 'Chỉ áp dụng khi Thanh toán 100%'), ('Dat_coc', 'Chỉ áp dụng cho Đặt cọc')], default='Tat_ca', max_length=20, verbose_name='Loại đơn áp dụng'),
        ),
    ]
