# Generated by Django 5.2.13 on 2026-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_khuyenmai_loai_don_ap_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioiThieuCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(default='Giới thiệu về EV STORE', max_length=200)),
                ('noi_dung', models.TextField()),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giới thiệu tổng quát',
            },
        ),
    ]
